### ISSUE TITLE
flashcards number 70 and higher commented in emf_karten_120219.tex

### ISSUE THREAD

**Issue by benkinooby** [latex4ei/Elektromagnetische-Feldtheorie#3]
Hi,
why are nearly half of all flashcards commented?
See
https://github.com/latex4ei/Elektromagnetische-Feldtheorie/blob/e38af7b45b1d82aa7c07625052d23529ae53b237/Karteikarten/emf_karten_120219.tex#L682

**Comment by hofbi** [comment]
I uncommented the remaining cards. Get the full set from https://github.com/latex4ei/Elektromagnetische-Feldtheorie/tree/gh-pages
